### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port

### ISSUE THREAD

**Issue by Sathiyarajan** [nilan3/kubernetes-ansible-centos#2]
@nilan3 
### getting the below failure while running kubernetes 
task path: /home/sathya/devops-pipeline/vagrant/roles/kubernetes-master/tasks/main.yml:17
fatal: [node2]: FAILED! => {"changed": true, "cmd": "kubectl get cs", "delta": "0:00:00.170477", "end": "2021-03-12 18:15:18.180072", "msg": "non-zero return code", "rc": 1, "start": "2021-03-12 18:15:18.009595", "stderr": "The connection to the server localhost:8080 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server localhost:8080 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

**Comment by YashAnand1** [comment]
Hi there - You were probably able to solve this issue but since I also faced it today, I would like to let you know that I was able to solve it by defining 'become: false' under my task that was related to interacting with Kubernetes. My playbook starts with 'become: true' and I cannot change this since most of the tasks in it need the sudo privilege.

For example, my playbook that ended up working for me was similar to this:
```
---
- hosts: chapter2
  become: yes
  ignore_errors: no
  gather_facts: no
  tasks:

# other tasks before this that require sudo privelege

    - name: Start Minikube
      ansible.builtin.shell: minikube start

    - name: Q2. Fetch ROLES
      ansible.builtin.shell: kubectl get nodes -o wide | grep -v ROLES | awk {'print $3'}
      register: ROLES_output
      become: no

    - name: Q3. Save content to file in /home/ansible/Desktop/out.txt
      ansible.builtin.copy:
        content: |
          ROLES={{ ROLES_output.stdout }}
        dest: /home/ansible/Desktop/out.txt

# other tasks after this that require sudo privelege
...
```
Here, I added `become: no` to the `Fetch Roles` task, which is required since minikube uses Docker that is not to be used with sudo priveleges.
